### PR TITLE
Use node 16 for releases

### LINKED ISSUE #620: Support node 16 LTS

### PR DESCRIPTION
**Pull request by ianhe8x**
Closes #620

### CODE REVIEW

**Comment by stwiname** [comment]
Out of scope of this PR, but maybe we want to consider specifying compatible node versions https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines

**Comment by ianhe8x** [comment]
polkadot-js does have one, since we depend on it, we share same node version requirements.

**Comment by wqsz7xn** [comment]
Trying to fix this but i'm getting timeouts on the subql/cli jsonrpc to fetch the genesis hash on polkadot. This doesn't happen on the pr run of the docker test image so i'm getting it's a location thing.

On another note fetching the genesis hash is crazy expensive? I'm getting >5sec (times out) for websockets and ~1sec for http for what seems like a pretty simple operation
```
● test jsonrpc client › Query polkadot's genesisHash via ws endpoint

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      10 |
      11 | describe('test jsonrpc client', () => {
    > 12 |   it("Query polkadot's genesisHash via ws endpoint", async () => {
```

**Comment by wqsz7xn** [comment]
Not sure what's up with the ci here. Running `yarn test:docker` on this branch yields all tests passing

```test_1      | Test Suites: 1 skipped, 34 passed, 34 of 35 total
test_1      | Tests:       9 skipped, 136 passed, 145 total
test_1      | Snapshots:   0 total
test_1      | Time:        522.119 s
test_1      | Ran all test suites.
test_1      | Force exiting Jest: Have you considered using `--detectOpenHandles` to detect async operations that kept running after all tests finished?
```

The action `pr.yml` isn't particularly special, it's just making a few more checks along the way in terms of linting and just calls `yarn test`. Maybe this is something weird with caching?

**Comment by ianhe8x** [comment]
the timeout issue could be just random

**Pull request merged**
