### PR TITLE
fix(codegen): undefined tstype for unsupported field type

### LINKED ISSUE #2001: 🐞 Bug: unsupported scalar type in json fields produces error
### Prerequisites

* [ ] Are you running the latest version(s)?
* [x] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [x] Did you search for an existing issue or pull request?

### Description

In [the codegen controller](https://github.com/subquery/subql/blob/889e86e88750ef7f9d2e36a6f6faaea57b9809c4/packages/cli/src/controller/codegen-controller.ts#L355) the error "Cannot read properties of undefined (reading 'tsType')" is produced thanks to unsupported type.

### Details

**Local Environment:** @subql/cli/3.5.1 darwin-arm64 node-v18.16.1

### Steps to Reproduce

create a new project using the subql CLI
```sh
subql init
```

In schema.graphql:
- Create json field
- Have field inside json be an enum
Then launch subquery codegen
```sh
yarn codegen
```

in the terminal you should see "Cannot read properties of undefined (reading 'tsType')"

### PR DESCRIPTION
**Pull request by ErikssonJoakim**
# Description
Removes erroneous type assertion in the `getTypeByScalarName` utility function.

Fixes #2001 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I have tested locally
- [x] I have performed a self review of my changes
- [ ] Updated any relevant documentation
- [x] Linked to any relevant issues
- [x] I have added tests relevant to my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] My code is up to date with the base branch
- [ ] I have updated relevant changelogs. [We suggest using chan](https://github.com/geut/chan/tree/main/packages/chan)

### CODE REVIEW

**Comment by bz888** [comment]
Are you able to add a test for this ?

**Comment by ErikssonJoakim** [comment]
@bz888 sure. I have a lot of failed tests though. I assume it's because I don't have all the credentials needed
```
Test Suites: 12 failed, 2 skipped, 49 passed, 61 of 63 total
Tests:       30 failed, 12 skipped, 268 passed, 310 total
Snapshots:   0 total
Time:        1073.661 s
```

**Review by bz888 — APPROVED** [review]

**Review by bz888 — COMMENTED** [review]
After testing this my on end, I am a little confused. 

Is this change purely for better error handling or is it supposed to be a fix for processing enums in jsonFields ?

**Comment by ErikssonJoakim** [comment]
@bz888 This is just a bug fix for the runtime error you get when the codegen tries to find the tsType of a scalar type that is not supported.

I have however made a logical error in the tests. It is to specific to test Enums, especially considering it's a type you might support in the future (I hope ❤️).

I hope this clears any doubts as to the purpose of the PR.

**Pull request merged**
