### PR TITLE
Allow specifying 'ipfs-headers' option to node

### PR DESCRIPTION
**Pull request by stwiname**
Effectively allows authorization for IPFS

Example flags:
*  ~~`--ipfs-headers "{ \"Authorization\": \"Bearer <Your-Auth-Token-Here>\"}"`~~
* `--ipfs-header "Authorization: Bearer <Your-Auth-Token-Here>" "X-Custom-Header: value"`
* `--ipfs-header "Authorization: Bearer <Your-Auth-Token-Here>"  --ipfs-header "X-Custom-Header: value"`

### CODE REVIEW

**Comment by ianhe8x** [comment]
The json escaping could be confusing. Is it possible to do `--ipfs-headers Authorization="Bearer <Your-Auth-Token-Here>"` like what curl does.

**Review by ianhe8x — APPROVED** [review]

**Comment by HZHAIX** [comment]
Thanks for fixing this 👍

**Comment by ianhe8x** [comment]
moonriver api is down at the moment, that's why tests failed.

**Comment by ianhe8x** [comment]
@jiqiang90 you might want to test it?

**Pull request closed without merging**
