### PR TITLE
Adds code-groups

### PR DESCRIPTION
**Pull request by seandotau**
Looks tidier.

### CODE REVIEW

**Review by jiqiang90 — APPROVED** [review]

**Comment by ianhe8x** [comment]
code-block isn't supported well by markdown.

**Comment by seandotau** [comment]
> code-block isn't supported well by markdown.

I see. I got the idea from https://vuepress.vuejs.org/guide/getting-started.html

**Comment by jamesbayly** [comment]
It doesn't necessarily break the markdown files and it certainly adds more to our main documentation website in Vuepress - i see no bad reason why we shouldn't roll this out

**Comment by jamesbayly** [comment]
@seandotau  are you going to add it to all other codeblocks in this PR?

**Comment by seandotau** [comment]
I've converted everything over I believe @jamesbayly

**Pull request merged**
