### PR TITLE
Feature/query historical state

### PR DESCRIPTION
**Pull request by Lpaydat**
Create plugins to handle the generated primary key and block height columns.
Modified a plugin to exclude generated primary key from where clause.
Update README

### CODE REVIEW

**Comment by jiqiang90** [comment]
Thanks for contribution @Lpaydat , we will look at it as soon as we can

**Comment by ianhe8x** [comment]
I haven't ran it locally, though I think it would be good to confirm a few things first.
1. I don't think you can still use foreignkey for relations. Image 
```
Table1： pid, id,  table2_id, _$block_height
A00, 1, B00, [1000,)

Table2: pid,id, data, _$block_height
B00, 1, value_old, [1000,1005)
B01, 1, value_new, [1005,)
```
At block 1000, A00 and B00 are inserted into db.
At block 1005, Table2(id:1) was updated to a new value, thus B01 was inserted and B00's blockheight was chaged from `[1000,)` to `[1000,1005)`

The following query should return different table2 records on different blockheight input
```
table1(blockheight: 1000) {
    nodes{
        table2{
          data
        }
}
}
// return value_old
table1(blockheight: 1005) {
    nodes{
        table2{
          data
        }
}
}
// return value_new
```
You can see foreign key is no use here.

2. if foreign key is not used, (which is also good for insert performance), then to understand the relation between entities, subql-query will need to read the graphql schema defined by user in their query project.

**Comment by jiqiang90** [comment]
@Lpaydat , can you provide an example schema (maybe include some data) for your work? 

I try to write one, and when i apply the blockHeight , I got this error.


```
 "errors": [
    {
      "message": "operator does not exist: bigint @> bigint",
      "locations": [

```

**Comment by Lpaydat** [comment]
@jiqiang90 Sorry for the delayed response; I haven't checked GitHub in a while.

I just updated the repo code after noticing that my earlier code did not solve the issue mentioned by Ian.
My approach may differ somewhat from Ian's in https://github.com/subquery/subql/issues/415 since I continue to rely on foreign keys but redirect the argument value from the `pid` column to the `id` column instead.

The database schema that I tested is as follows:

```
create table hellos
(
  pid                 text    not null    primary key,  -- random generated, but first item needs to use provided `id` as its `pid`
  id                  text    not null,
  value               text    not null,
  _$block_height      int8range  not null
);
```

and

```
create table demos
(
    pid              text    not null   primary key, -- again, first item needs to use the provided `id` is its `pid`
    id               text    not null, -- original primary key
    field            text    not null,
    _$block_height   int8range not null, -- new added versioned field
    hello_id         text    REFERENCES hellos(pid)    -- foreign key to Hello entity
);
```

```
INSERT INTO
    hellos (pid, id, value, _$block_height)
VALUES
    ('B01', 'B01', '0-100', '[0,100)'),
    ('aaa', 'B01', '100-250', '[100,250)'),
    ('bbb', 'B01', '250++', '[250,)');
```

```
INSERT INTO
    demos (pid, id, field, _$block_height, hello_id)
VALUES
    ('A01', 'A01', '0-150', '[0,150)', 'B01'),
    ('xxx', 'A01', '150++', '[150,)', 'B01');
```

The root `blockHeight` value will be the default for that root query and will be passed down to its children, but it will be reset at each root query level.
At the child level, the user can specify a new `blockHeight` which will override the default 'blockHeight' for that field only.

**Pull request closed without merging**
