### PR TITLE
Support Env File & Env Command

### PR DESCRIPTION
**Pull request by AK46rocks**
Issue: https://github.com/subquery/subql/issues/2217

# Description
- Created expected .env files and added local env files in .gitignore
```javascript
.env
.env.local 
.env.develop
.env.develop.local
```
Added **CHAIN_ID** and **ENDPOINT**  in all the .env files dynamically fetching from  `project.ts`
```javascript
// Example .env
ENDPOINT=https://opbnb-mainnet-rpc.bnbchain.org
CHAIN_ID=204
```
User can configure .env files as per there requirement
Multiple comma separated ENDPOINT can be added in the .env file.
```javascript
ENDPOINT=https://opbnb-mainnet-rpc.bnbchain.org,https://polygon.api.onfinality.io/public
```

- Imported dotenv package and added respective config code in `project.ts` for development or production
```javascript
import * as dotenv from 'dotenv';
import path from 'path';

const mode = process.env.NODE_ENV || 'production';
// Load the appropriate .env file
const dotenvPath = path.resolve(process.cwd(), `.env${mode !== 'production' ? `.${mode}` : ''}`);
dotenv.config({ path: dotenvPath });

const project: EthereumProject = {
   .....
  network: {
    chainId: process.env.chainId,
    endpoint: process.env.ENDPOINT!.split(',') as string[] | string,
  },
```
- In `package.json` added scripts for build prod / develop and also added **"dotenv"** in devDependencies
```javascript
  scripts: {
      ......
    "build": "subql codegen && subql build", // default is production
    "build:develop": "NODE_ENV=develop subql codegen && NODE_ENV=develop subql build",
  }
  "devDependencies": {
      .....
    "dotenv": "latest"
  }
 ```

## Tests
- Check dotenv configuration is properly added and working in `project.ts`
- Check if the environment variables are loaded correctly from the `.env` file based on the environment mode. (`production`, `develop`)
- Ensure that the production build script works as expected. The production build script should generate the necessary artifacts for production deployment without errors.
- Verify that the development build script works as expected. The development build script should generate the necessary artifacts for development without errors and use the environment variables specific to the development environment.
-  Ensure that `.env.local` and `.env.develop.local` files are ignored in version control. 

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist

- [x] I have tested locally
- [x] I have performed a self review of my changes
- [x] Updated any relevant documentation
- [x] Linked to any relevant issues
- [x] I have added tests relevant to my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] My code is up to date with the base branch
- [x] I have updated relevant changelogs using [chan CLI](https://github.com/geut/chan/tree/main/packages/chan)

### CODE REVIEW

**Review by stwiname — COMMENTED** [review]
Thanks for your PR,  the code looks good

There are a couple of things missing:
* Changelogs
* Tests, it would be good to have a test that the modifications to the files results in the desired outputs
* Documentation for how to use Env can be added here https://github.com/subquery/documentation

**Comment by AK46rocks** [comment]
> Thanks for your PR, the code looks good
> 
> There are a couple of things missing:
> 
> * Changelogs
> * Tests, it would be good to have a test that the modifications to the files results in the desired outputs
> * Documentation for how to use Env can be added here https://github.com/subquery/documentation

- Added Changelogs.
- Added Tests in PR description.
- Documentation is updated.
   - PR: https://github.com/subquery/documentation/pull/507

**Review by jiqiang90 — APPROVED** [review]

**Review by stwiname — CHANGES_REQUESTED** [review]
I've noticed that some tests are failing with new errors, can you please address this issue

```
Cli publish › v1.0.0 should deploy

    Failed to generate manifest from typescript /var/folders/th/bb0sn1qj7qx5_l9y509hqn8h0000gn/T/8WwKYF/mocked_starter/project.ts, Failed to build /var/folders/th/bb0sn1qj7qx5_l9y509hqn8h0000gn/T/8WwKYF/mocked_starter/project.ts: TypeError: Cannot read properties of undefined (reading 'split')

      75 |     const script = tsNodeService.compile(
      76 |       requireScriptWrapper(formatPath(projectManifestEntry), formatPath(projectYamlPath)),
    > 77 |       'inline.ts'
         |               ^
      78 |     );
      79 |
      80 |     // Run compiled code

      at buildManifestFromLocation (packages/cli/src/utils/build.ts:77:15)
      at async Codegen.run (packages/cli/src/commands/codegen/index.ts:24:13)
      at async Codegen._run (node_modules/@oclif/core/lib/command.js:117:22)
      at async createTestProject (packages/cli/src/controller/publish-controller.spec.ts:67:5)
      at async Object.<anonymous> (packages/cli/src/controller/publish-controller.spec.ts:110:22)
```

**Comment by AK46rocks** [comment]
> I've noticed that some tests are failing with new errors, can you please address this issue
> 
> ```
> Cli publish › v1.0.0 should deploy
> 
>     Failed to generate manifest from typescript /var/folders/th/bb0sn1qj7qx5_l9y509hqn8h0000gn/T/8WwKYF/mocked_starter/project.ts, Failed to build /var/folders/th/bb0sn1qj7qx5_l9y509hqn8h0000gn/T/8WwKYF/mocked_starter/project.ts: TypeError: Cannot read properties of undefined (reading 'split')
> 
>       75 |     const script = tsNodeService.compile(
>       76 |       requireScriptWrapper(formatPath(projectManifestEntry), formatPath(projectYamlPath)),
>     > 77 |       'inline.ts'
>          |               ^
>       78 |     );
>       79 |
>       80 |     // Run compiled code
> 
>       at buildManifestFromLocation (packages/cli/src/utils/build.ts:77:15)
>       at async Codegen.run (packages/cli/src/commands/codegen/index.ts:24:13)
>       at async Codegen._run (node_modules/@oclif/core/lib/command.js:117:22)
>       at async createTestProject (packages/cli/src/controller/publish-controller.spec.ts:67:5)
>       at async Object.<anonymous> (packages/cli/src/controller/publish-controller.spec.ts:110:22)
> ```

This error is resolved.

**Review by stwiname — APPROVED** [review]

**Pull request merged**
