### PR TITLE
change license for starter, change default specVersion

### PR DESCRIPTION
**Pull request by lachlan1m**
#612 #627

### CODE REVIEW

**Review by ianhe8x — APPROVED** [review]

**Comment by ianhe8x** [comment]
@lachlan1m do you have a companion PR in the [starter repo](https://github.com/subquery/subql-starter/pulls)? 
* make a branch for 0.0.1 spec
* clean the main branch, only leave README there. (or switch 0.2.0 branch to main)
* add MIT license file to both 0.0.1 and 0.2.0 branches.

**Comment by lachlan1m** [comment]
> @lachlan1m do you have a companion PR in the [starter repo](https://github.com/subquery/subql-starter/pulls)?
> 
> * make a branch for 0.0.1 spec
> * clean the main branch, only leave README there. (or switch 0.2.0 branch to main)
> * add MIT license file to both 0.0.1 and 0.2.0 branches.

I'll add one

**Comment by lachlan1m** [comment]
https://github.com/subquery/subql-starter/pull/33

**Comment by lachlan1m** [comment]
@ianhe8x can you also remove https://github.com/subquery/subql-starter/tree/v0.0.1-manifest I doubled up the branch

**Comment by ianhe8x** [comment]
@lachlan1m Pls update [ init-controller.ts ](https://github.com/subquery/subql/blob/0dcc89affa0284650b08a132e2157aada9a0c09a/packages/cli/src/controller/init-controller.ts#L19)
So that when user choose to checkout v0.0.1 project, we will clone from correct branch.

**Comment by lachlan1m** [comment]
> @lachlan1m Pls update [ init-controller.ts ](https://github.com/subquery/subql/blob/0dcc89affa0284650b08a132e2157aada9a0c09a/packages/cli/src/controller/init-controller.ts#L19) So that when user choose to checkout v0.0.1 project, we will clone from correct branch.

done

**Review by ianhe8x — APPROVED** [review]

**Pull request merged**
