### PR TITLE
Allow set query-complexity for query

### PR DESCRIPTION
**Pull request by jiqiang90**
```
query{
  starterEntities(first:5){
    nodes{
      field1
    }
  }
}

```
This will count complexity to 3

default value is 10,  to change this by set `query-complexity=20`

### CODE REVIEW

**Review by stwiname — APPROVED** [review]
Is there more to complexity than just depth? Its hard to know if 10 is an appropriate default

**Comment by ianhe8x** [comment]
I forget where I saw it, but anyway there's a cool idea that we can return the complexity in response header

**Comment by jiqiang90** [comment]
> I forget where I saw it, but anyway there's a cool idea that we can return the complexity in response header

we just need to add this .

```
 willSendResponse({ response }) {
          response.extensions = response.extensions || {};
          response.extensions.complexity = complexity;
          response.extensions.maxComplexity = maxComplexity;
        },
```

**Comment by ianhe8x** [comment]
> > I forget where I saw it, but anyway there's a cool idea that we can return the complexity in response header
> 
> we just need to add this .
> 
> ```
>  willSendResponse({ response }) {
>           response.extensions = response.extensions || {};
>           response.extensions.complexity = complexity;
>           response.extensions.maxComplexity = maxComplexity;
>         },
> ```

@jiqiang90 Can you add this and make sure 10 is enough for our usecase.

**Comment by ianhe8x** [comment]
@jiqiang90 Some test failures about graphql

**Comment by jamesbayly** [comment]
I like returning the query complexity in the header
I do not think we should set a default in SubQL and it will only piss people off when running it locally
We should only set a default in the managed service, we need to carefully consider the number

**Comment by jamesbayly** [comment]
I'm very against setting a default value in this package actually

**Comment by jiqiang90** [comment]
> I like returning the query complexity in the header I do not think we should set a default in SubQL and it will only piss people off when running it locally We should only set a default in the managed service, we need to carefully consider the number

Sounds reasonable to me, I will remove the restriction,  only implement plugin when `query-complexity` is set,

**Review by stwiname — APPROVED** [review]

**Pull request merged**
