### PR TITLE
(feat):add support for graphiql

### PR DESCRIPTION
**Pull request by 0xJoichiro**
# Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue) #1515 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] I have tested locally
- [ ] I have performed a self review of my changes
- [ ] Updated any relevant documentation
- [x] Linked to any relevant issues
- [ ] I have added tests relevant to my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] My code is up to date with the base branch
- [ ] I have updated relevant changelogs. [We suggest using chan](https://github.com/geut/chan/tree/main/packages/chan)

### CODE REVIEW

**Comment by stwiname** [comment]
Hi @0xJoichiro thank you for contributing to SubQuery. This is on the right track but it should use the [SubQuery styled](https://github.com/subquery/subquery-component-library/tree/master/components/common/GraphiQL) version of GraphiQL. Could you please update to use this version.

**Comment by 0xJoichiro** [comment]
> Hi @0xJoichiro thank you for contributing to SubQuery. This is on the right track but it should use the [SubQuery styled](https://github.com/subquery/subquery-component-library/tree/master/components/common/GraphiQL) version of GraphiQL. Could you please update to use this version.

understood

**Comment by 0xJoichiro** [comment]
@stwiname ser,we do not have a similar cdn for subql-components working on one and would add a pr there as well for the cdn support added an issue there => https://github.com/subquery/subquery-component-library/issues/105

**Comment by stwiname** [comment]
@0xJoichiro can it be added as a dependency through npm?

**Comment by 0xJoichiro** [comment]
> @0xJoichiro can it be added as a dependency through npm?

the issue was finished from your end it seems and would be making final changes asap

**Comment by stwiname** [comment]
@0xJoichiro do you plan on completing this?

**Comment by stwiname** [comment]
Hi @0xJoichiro this should be unblocked now if you wished to complete this. 

See the dependent issue for details https://github.com/subquery/subquery-component-library/issues/108

**Pull request closed without merging**
