### PR TITLE
Hotfix: Ensure either secure and insecure Postgres connection can be used

### PR DESCRIPTION
**Pull request by darwinsubramaniam**
# Description
#1513 This issue is to ensure the unsecured database connection will still able to work
The merge of #1513, forced the ssl database connection

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] I have tested locally
- [x] I have performed a self review of my changes
- [x] Updated any relevant documentation
- [ ] Linked to any relevant issues
- [ ] I have added tests relevant to my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] My code is up to date with the base branch

### CODE REVIEW

**Comment by darwinsubramaniam** [comment]
Hi @stwiname ,

The merge of #1513 , break the connection to insecure database. 
This will fix it , performed test using both insecure and secure database.

**Comment by darwinsubramaniam** [comment]
Documentation update accordingly in this PR https://github.com/subquery/documentation/pull/286

**Comment by jiqiang90** [comment]
Hi @darwinsubramaniam , can you take a look change at https://github.com/subquery/subql/blob/2f9b4bb07c94f103b7968b99f518079c9dde65a4/packages/node-core/src/db/db.module.ts#L69. 

In this branch we support cockroach and ssl by default, if db not support ssl it will retry connection without it. I think this pr is duplex with it

**Comment by stwiname** [comment]
Hi @darwinsubramaniam we have fixed this in an unrelated PR https://github.com/subquery/subql/pull/1521

**Comment by darwinsubramaniam** [comment]
Hi @jiqiang90  and @stwiname , 

That's good :). Ok, we can ignore this PR .

**Pull request closed without merging**
