### PR TITLE
Enable for better inheritance of generated entity modeld

### PR DESCRIPTION
**Pull request by filo87**
# Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have tested locally
- [x] I have performed a self review of my changes
- [ ] Updated any relevant documentation
- [x] Linked to any relevant issues
- [ ] I have added tests relevant to my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] My code is up to date with the base branch

### CODE REVIEW

**Comment by filo87** [comment]
Implements #1373

**Comment by jiqiang90** [comment]
Thanks @filo87 for your contribution, we will review this get back to you shortly

**Comment by jiqiang90** [comment]
looks good to me

**Review by stwiname — APPROVED** [review]

**Comment by jamesbayly** [comment]
Thanks for the contribution @filo87!

**Pull request merged**
