### PR TITLE
[release] 20221027

### PR DESCRIPTION
**Pull request by stwiname**

### CODE REVIEW

**Comment by deverka** [comment]
@stwiname timestamp is included in this release, right? What about `unfinalized` blocks indexing?

**Comment by stwiname** [comment]
> @stwiname timestamp is included in this release, right? What about `unfinalized` blocks indexing?

Unfinalized blocked is not in this release.

**Comment by deverka** [comment]
> > @stwiname timestamp is included in this release, right? What about `unfinalized` blocks indexing?
> 
> Unfinalized blocked is not in this release.

I thought we want to release it together?

**Review by deverka — APPROVED** [review]

**Comment by stwiname** [comment]
> I thought we want to release it together?

Its taking longer than expected and users are waiting on other features

**Comment by deverka** [comment]
What about docs? @stwiname

**Pull request merged**
